# Generated by Django 3.2.5 on 2021-07-24 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='job name')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('category', models.CharField(choices=[('Full Time', 'Full Time'), ('Contract', 'Contract')], max_length=50, verbose_name='category')),
            ],
        ),
        migrations.AddField(
            model_name='applicants',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.listing', verbose_name=''),
            preserve_default=False,
        ),
    ]
